version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region us-west-2)
  build:
    commands:
      - chmod a+x ./codebuild-docker-build.sh
      - bash ./codebuild-docker-build.sh
artifacts:
  files:
    - ./**/*
# http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
