FROM quay.io/byuoit/node-oracledb
LABEL maintainer = Daniel Hancock <daniel_hancock@byu.edu>

RUN apt-get update && \
    apt-get install git -y && \
    apt-get install build-essential -y && \
    apt-get clean

WORKDIR /usr/src/
ADD . .
RUN npm install

EXPOSE 3000
CMD node index.js