version: 1

name: byuapi-persons

pipelines:
  dev:
    phases:
    - type: github
      name: Github
      owner: byu-oit
      repo: byuapi-persons
      branch: master
    - type: codebuild
      name: Build
      build_image: aws/codebuild/docker:1.12.1
    - type: handel
      name: DevDeploy
      environments_to_deploy:
      - dev
# https://handel-codepipeline.readthedocs.io
